parent: "configs/ours_base.yaml"
save_step: 400

frame_start: 0
frame_step: 0
frame_num: -1

# dataset params:
source_path: "./data/Ours/corridor"
save_path: "output/dataset/Ours/corridor"

use_gt_pose: False