parent: "/root/code/rtgslam_ros_ws/src/rtgslam_ros/rtgslam_ros/configs/ours_base.yaml"
save_step: 400

frame_start: 0
frame_step: 0
frame_num: -1

# dataset params:
source_path: "/root/code/datasets/hotel"
save_path: "/root/code/output/dataset/ours/hotel"

use_gt_pose: False