name: RTG-SLAM
channels:
  - pytorch
  - conda-forge
  - nvidia
  - pytorch3d
  - defaults
dependencies:
  - cudatoolkit=11.7
  - plyfile
  - python=3.9.0
  - pytorch=1.13.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm
  - tensorboard
  - torchmetrics
  - pytorch3d
  - pip:
    - pytorch_msssim
    - trimesh
    - scikit-image
    - open3d
    - pyyaml
    - scipy
    - opencv-python
    - matplotlib
    - GPUtil
    - submodules/cuda_utils
    - submodules/diff-gaussian-rasterizer-depth
    - submodules/simple-knn