parent: "/root/code/rtgslam_ros_ws/src/rtgslam_ros/rtgslam_ros/configs/tum_base.yaml"

frame_start: 0
frame_step: 0
frame_num: -1

# dataset params:
source_path: "/root/code/datasets/tum/rgbd_dataset_freiburg1_desk"
save_path: "/root/code/output/tum/fr1_desk"

orb_settings_path: "/root/code/rtgslam_ros_ws/src/rtgslam_ros/rtgslam_ros/configs/orb_config/tum1.yaml"
